version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@Jayraj
      POSTGRES_DB: streaming
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend          # 👈 Build context is backend folder
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "3001:${PORT}"
    depends_on:
      - postgres
    env_file:
      - .env                      # 👈 Loads from root .env
    restart: unless-stopped
    volumes:
      - ./backend:/app           # 👈 Map backend code
      - /app/node_modules
    working_dir: /app
    command: npm run dev

volumes:
  pgdata:
